[build]
  command = "npm run build"
  publish = "."

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/client"
  to = "/client.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "no-store"
